[tool.poetry]
name = "kazam"
version = "0.1.0"
description = ""
authors = ["chrisaddy <chris.william.addy@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
shazamio = "^0.3.1.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
